-- Real Postgres SQL - this is genuinely running against Postgres, not H2's
-- Postgres-compatibility mode. IDENTITY columns and VARCHAR both work identically to
-- how they read against H2 in lesson 36 - this migration file needed no changes at all.
CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);
